# Generated by Django 4.2.16 on 2024-09-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='status',
            field=models.TextField(max_length=500),
        ),
    ]
